### PR TITLE
shouldInlineFonts if fonts or inlineFonts = true

### PR DESCRIPTION
**Pull request by newsroomdev**
## Description of changes

This change updates `shouldInlineFonts` to evaluate as described in the README: true if either the `fonts` or `inlineFonts` option is set to true. At the moment, both `fonts` and `inlineFonts` would need to be set to true for the whole statement to be truthy.

-   `inlineFonts` **[Boolean](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Boolean)** Inline critical font-face rules _(default: `false`)_
-   `preloadFonts` **[Boolean](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Boolean)** Preloads critical fonts _(default: `true`)_
-   `fonts` **[Boolean](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Boolean)** Shorthand for setting `inlineFonts`+`preloadFonts`-   Values:
    -   `true` to inline critical font-face rules and preload the fonts
    -   `false` to don't inline any font-face rules and don't preload fonts

@developit

### CODE REVIEW

**Comment by newsroomdev** [comment]
@googlebot I signed it!

**Comment by newsroomdev** [comment]
cc @developit

**Comment by developit** [comment]
Hiya - sorry for taking a bit to get around to this. I'm not entirely sure what the best option is for this, since the property is currently a tri-state:

- `fonts: false`: don't inline or preload anything
- `fonts: true`: inline and preload everything
- `fonts: undefined`: preload, but don't inline (this is the default)

**Comment by janicklas-ralph** [comment]
This could be a breaking change since users might be expecting a certain behavior.

Maybe we can rethink the `fonts` flag? Maybe remove it given the confusion and also the additional font optimization (WIP) makes it less extensible.

**Comment by developit** [comment]
Removing it seems like the way to go.

**Comment by kara** [comment]
Closing this PR because ownership of Critters has moved to the Nuxt team, who will be maintaining the project going forward. This repo is archived and won't receive any future updates.
 
If the PR is still relevant, please re-post it to the actively-maintained fork at https://github.com/danielroe/beasties.

**Pull request closed without merging**
